$path = "pages\CaseDetail.tsx"
$content = Get-Content -Path $path -Raw -Encoding UTF8
$content = $content -replace 'w - full', 'w-full'
$content = $content -replace 'p - 2', 'p-2'
$content = $content -replace 'border - blue', 'border-blue'
$content = $content -replace 'border - gray', 'border-gray'
$content = $content -replace 'border - transparent', 'border-transparent'
$content = $content -replace 'bg - blue', 'bg-blue'
$content = $content -replace 'bg - gray', 'bg-gray'
$content = $content -replace 'bg - green', 'bg-green'
$content = $content -replace 'bg - indigo', 'bg-indigo'
$content = $content -replace 'bg - white', 'bg-white'
$content = $content -replace 'text - blue', 'text-blue'
$content = $content -replace 'text - gray', 'text-gray'
$content = $content -replace 'text - green', 'text-green'
$content = $content -replace 'text - white', 'text-white'
$content = $content -replace 'px - 2', 'px-2'
$content = $content -replace 'px - 3', 'px-3'
$content = $content -replace 'px - 4', 'px-4'
$content = $content -replace 'py - 0.5', 'py-0.5'
$content = $content -replace 'py - 1.5', 'py-1.5'
$content = $content -replace 'py - 3', 'py-3'
$content = $content -replace 'text - sm', 'text-sm'
$content = $content -replace 'text - xs', 'text-xs'
$content = $content -replace 'font - bold', 'font-bold'
$content = $content -replace 'font - medium', 'font-medium'
$content = $content -replace 'border - b - 2', 'border-b-2'
$content = $content -replace 'items - center', 'items-center'
$content = $content -replace 'outline - none', 'outline-none'
$content = $content -replace 'min - h - \[40px\]', 'min-h-[40px]'
$content = $content -replace 'flex - 1', 'flex-1'
$content = $content -replace 'whitespace - nowrap', 'whitespace-nowrap'

Set-Content -Path $path -Value $content -Encoding UTF8
Write-Host "Fixed CaseDetail.tsx"
