
import { Case, CaseStatusLog, CommissionRule, SettlementConfig, Partner } from '../types';
import { subDays, addDays, format } from 'date-fns';
import { DEFAULT_SUMMARY_TEMPLATE, DEFAULT_AI_PROMPT } from '../constants';

const DEFAULT_RULES: CommissionRule[] = [
  { ruleId: '1', minFee: 400, maxFee: 440, commission: 100, fullPayoutThreshold: 100, priority: 1, active: true, updatedAt: '2024-02-01' },
  { ruleId: '2', minFee: 500, maxFee: 550, commission: 150, fullPayoutThreshold: 150, priority: 1, active: true, updatedAt: '2024-02-01' },
  { ruleId: '3', minFee: 600, maxFee: 660, commission: 200, fullPayoutThreshold: 200, priority: 1, active: true, updatedAt: '2024-02-01' },
];

const DEFAULT_CONFIG: SettlementConfig = {
  cutoffDay: 0, // Sun
  payoutDay: 2, // Tue
  payoutWeekDelay: 0,
  downPaymentPercentage: 10,
  firstPayoutPercentage: 50
};

export const MOCK_PARTNERS: Partner[] = [
  {
    partnerId: 'P001',
    name: '태산 법률사무소',
    active: true,
    settlementConfig: { ...DEFAULT_CONFIG },
    commissionRules: JSON.parse(JSON.stringify(DEFAULT_RULES)), // Deep copy for mock
    summaryTemplate: DEFAULT_SUMMARY_TEMPLATE,
    aiPromptTemplate: DEFAULT_AI_PROMPT,
    requiredFields: ['childrenCount', 'depositLoan', 'spouseAssets', 'creditCard', 'history', 'assets']
  },
  {
    partnerId: 'P002',
    name: '율도 법무법인',
    active: true,
    settlementConfig: {
      cutoffDay: 5, // Fri
      payoutDay: 1, // Mon
      payoutWeekDelay: 1, // Next week
      downPaymentPercentage: 20,
      firstPayoutPercentage: 40
    },
    commissionRules: [
      { ruleId: '10', minFee: 300, maxFee: 0, commission: 80, fullPayoutThreshold: 100, priority: 1, active: true, updatedAt: '2024-02-01' }
    ],
    summaryTemplate: `[율도 접수]\n고객명: {{customerName}}\n전화: {{phone}}\n특이사항: {{specialMemo}}`,
    aiPromptTemplate: DEFAULT_AI_PROMPT,
    requiredFields: [] // Minimal fields
  },
  {
    partnerId: 'P003',
    name: '화려 법률사무소',
    active: true,
    settlementConfig: { ...DEFAULT_CONFIG },
    commissionRules: JSON.parse(JSON.stringify(DEFAULT_RULES)),
    summaryTemplate: DEFAULT_SUMMARY_TEMPLATE,
    aiPromptTemplate: DEFAULT_AI_PROMPT,
    requiredFields: ['childrenCount', 'depositLoan', 'spouseAssets', 'creditCard', 'history', 'assets']
  }
];

export const MOCK_INBOUND_PATHS = ['틱톡 광고', '메타 광고', '지인 소개', '블로그', '유튜브', '구글 검색'];

export const MOCK_CASES: Case[] = [
  {
    caseId: '1001',
    partnerId: 'P001',
    createdAt: subDays(new Date(), 10).toISOString(),
    updatedAt: subDays(new Date(), 1).toISOString(),
    status: '재통화 예정',
    statusUpdatedAt: subDays(new Date(), 1).toISOString(),
    managerName: 'Mark',
    caseType: '개인회생',
    inboundPath: '틱톡 광고',
    preInfo: '신청 메모: 부채가 많아서 걱정입니다.\n통화 가능 시간: 오후 2시 이후',
    aiSummary: '',
    customerName: '홍길동',
    phone: '010-1234-5678',
    birth: '1980',
    gender: '남',
    region: '서울',
    jobTypes: ['직장인'],
    insurance4: '가입',
    maritalStatus: '기혼',
    childrenCount: 2,
    incomeDetails: { salary: 300 },
    incomeNet: 300,
    loanMonthlyPay: 50,
    housingType: '전세',
    housingDetail: '아파트',
    deposit: 20000,
    rent: 0,
    rentContractor: '본인',
    assets: [
      { id: '1', owner: '본인', type: '자동차', amount: 2000, loanAmount: 500, desc: '소나타' }
    ],
    creditLoan: [{ id: 'cl-1', amount: 1000, desc: '햇살론' }],
    historyType: '없음',
    depositHistory: [],
    reminders: [{
      id: 'reminder-1',
      datetime: format(addDays(new Date(), 0), 'yyyy-MM-dd 14:00'),
      type: '통화'
    }],
    specialMemo: [{
      id: 'memo-1001-1',
      createdAt: subDays(new Date(), 1).toISOString(),
      content: '부인 몰래 진행 원함'
    },
    {
      id: 'memo-1001-2',
      createdAt: subDays(new Date(), 5).toISOString(),
      content: '5일 전 통화: 서류 준비 요청'
    }],
    recordings: []
  },
  {
    caseId: '1002',
    partnerId: 'P002',
    createdAt: subDays(new Date(), 5).toISOString(),
    updatedAt: subDays(new Date(), 5).toISOString(),
    status: '신규접수',
    statusUpdatedAt: subDays(new Date(), 5).toISOString(),
    managerName: 'Mark',
    caseType: '파산',
    inboundPath: '메타 광고',
    preInfo: '',
    aiSummary: '',
    customerName: '김철수',
    phone: '010-9876-5432',
    birth: '1992',
    gender: '남',
    region: '경기',
    jobTypes: ['개인사업자', '프리랜서'],
    insurance4: '미가입',
    maritalStatus: '미혼',
    childrenCount: 0,
    incomeDetails: { business: 400, freelance: 100 },
    incomeNet: 500,
    loanMonthlyPay: 200,
    housingType: '월세',
    housingDetail: '빌라',
    deposit: 1000,
    rent: 50,
    rentContractor: '본인',
    assets: [],
    creditLoan: [],
    historyType: '없음',
    specialMemo: [],
    depositHistory: [],
    reminders: [],
    recordings: []
  },
  // --- 추가된 15개의 가상 데이터 ---
  {
    caseId: '1003',
    partnerId: 'P001',
    createdAt: subDays(new Date(), 0).toISOString(),
    updatedAt: subDays(new Date(), 0).toISOString(),
    status: '신규접수',
    statusUpdatedAt: subDays(new Date(), 0).toISOString(),
    managerName: 'Mark',
    caseType: '개인회생',
    inboundPath: '지인 소개',
    customerName: '이영희',
    phone: '010-1111-2222',
    birth: '1985',
    gender: '여',
    region: '부산',
    jobTypes: ['직장인'],
    insurance4: '가입',
    maritalStatus: '미혼',
    childrenCount: 0,
    incomeDetails: { salary: 250 },
    incomeNet: 250,
    loanMonthlyPay: 80,
    housingType: '월세',
    housingDetail: '오피스텔',
    deposit: 500,
    rent: 60,
    rentContractor: '본인',
    assets: [],
    creditLoan: [{ id: 'cl-2', amount: 3000, desc: '카드론' }],
    historyType: '없음',
    specialMemo: [],
    depositHistory: [],
    reminders: [],
    recordings: []
  },
  {
    caseId: '1004',
    partnerId: 'P001',
    createdAt: subDays(new Date(), 1).toISOString(),
    updatedAt: subDays(new Date(), 1).toISOString(),
    status: '부재',
    statusUpdatedAt: subDays(new Date(), 1).toISOString(),
    managerName: 'Mark',
    caseType: '개인회생',
    inboundPath: '유튜브',
    customerName: '박민수',
    phone: '010-3333-4444',
    birth: '1978',
    gender: '남',
    region: '인천',
    jobTypes: ['개인사업자'],
    insurance4: '미가입',
    maritalStatus: '기혼',
    childrenCount: 1,
    incomeDetails: { business: 500 },
    incomeNet: 500,
    loanMonthlyPay: 150,
    housingType: '자가',
    housingDetail: '아파트',
    ownHousePrice: 35000,
    ownHouseLoan: 20000,
    ownHouseOwner: '본인',
    deposit: 0, rent: 0,
    assets: [{ id: '2', owner: '본인', type: '자동차', amount: 3000, loanAmount: 0, desc: '그랜저' }],
    creditLoan: [{ id: 'cl-3', amount: 5000, desc: '사업자대출' }],
    historyType: '없음',
    specialMemo: [],
    depositHistory: [],
    reminders: [{ id: 'rm-1004', datetime: format(addDays(new Date(), 1), 'yyyy-MM-dd 10:00'), type: '통화' }],
    recordings: []
  },
  {
    caseId: '1005',
    partnerId: 'P003',
    createdAt: subDays(new Date(), 2).toISOString(),
    updatedAt: subDays(new Date(), 2).toISOString(),
    status: '상담중',
    statusUpdatedAt: subDays(new Date(), 2).toISOString(),
    managerName: 'Mark',
    caseType: '신용회복',
    inboundPath: '블로그',
    customerName: '최지우',
    phone: '010-5555-6666',
    birth: '1990',
    gender: '여',
    region: '대구',
    jobTypes: ['프리랜서'],
    insurance4: '미가입',
    maritalStatus: '미혼',
    childrenCount: 0,
    incomeDetails: { freelance: 180 },
    incomeNet: 180,
    loanMonthlyPay: 40,
    housingType: '무상거주',
    housingDetail: '기타',
    freeHousingOwner: '부모님',
    deposit: 0, rent: 0,
    assets: [],
    creditLoan: [{ id: 'cl-4', amount: 1500, desc: '저축은행' }],
    historyType: '없음',
    specialMemo: [{ id: 'm-1005', createdAt: subDays(new Date(), 2).toISOString(), content: '워크아웃과 회생 비교 중' }],
    depositHistory: [],
    reminders: [{ id: 'rm-1005', datetime: format(addDays(new Date(), 2), 'yyyy-MM-dd 14:00'), type: '통화' }],
    recordings: []
  },
  {
    caseId: '1006',
    partnerId: 'P002',
    createdAt: subDays(new Date(), 3).toISOString(),
    updatedAt: subDays(new Date(), 0).toISOString(),
    status: '계약 완료',
    statusUpdatedAt: subDays(new Date(), 0).toISOString(),
    managerName: 'Mark',
    caseType: '개인회생',
    inboundPath: '메타 광고',
    customerName: '정우성',
    phone: '010-7777-8888',
    birth: '1982',
    gender: '남',
    region: '서울',
    jobTypes: ['직장인'],
    insurance4: '가입',
    maritalStatus: '이혼',
    childrenCount: 1,
    incomeDetails: { salary: 450 },
    incomeNet: 450,
    loanMonthlyPay: 120,
    housingType: '전세',
    housingDetail: '빌라',
    deposit: 15000,
    rent: 0,
    rentContractor: '본인',
    depositLoanAmount: 10000,
    assets: [],
    creditLoan: [{ id: 'cl-5', amount: 8000, desc: '은행신용' }],
    creditCardUse: '사용',
    creditCardAmount: 2000,
    historyType: '없음',
    contractAt: format(subDays(new Date(), 0), 'yyyy-MM-dd'),
    contractFee: 200,
    specialMemo: [],
    depositHistory: [],
    reminders: [],
    recordings: []
  },
  {
    caseId: '1007',
    partnerId: 'P001',
    createdAt: subDays(new Date(), 7).toISOString(),
    updatedAt: subDays(new Date(), 1).toISOString(),
    status: '1차 입금완료',
    statusUpdatedAt: subDays(new Date(), 1).toISOString(),
    managerName: 'Mark',
    caseType: '파산',
    inboundPath: '지인 소개',
    customerName: '강동원',
    phone: '010-9999-0000',
    birth: '1955',
    gender: '남',
    region: '광주',
    jobTypes: ['무직'],
    insurance4: '미가입',
    maritalStatus: '기혼',
    childrenCount: 0,
    incomeDetails: {},
    incomeNet: 0,
    loanMonthlyPay: 0,
    housingType: '월세',
    housingDetail: '단독주택',
    deposit: 500,
    rent: 30,
    rentContractor: '배우자',
    assets: [],
    creditLoan: [{ id: 'cl-6', amount: 4000, desc: '대부업체' }],
    historyType: '없음',
    contractAt: format(subDays(new Date(), 5), 'yyyy-MM-dd'),
    contractFee: 180,
    deposit1Amount: 100,
    deposit1Date: format(subDays(new Date(), 1), 'yyyy-MM-dd'),
    specialMemo: [{ id: 'm-1007', createdAt: subDays(new Date(), 7).toISOString(), content: '고령으로 인한 소득 활동 불가' }],
    depositHistory: [],
    reminders: [],
    recordings: []
  },
  {
    caseId: '1008',
    partnerId: 'P001',
    createdAt: subDays(new Date(), 15).toISOString(),
    updatedAt: subDays(new Date(), 10).toISOString(),
    status: '진행불가',
    statusUpdatedAt: subDays(new Date(), 10).toISOString(),
    managerName: 'Mark',
    caseType: '개인회생',
    inboundPath: '틱톡 광고',
    customerName: '손예진',
    phone: '010-1212-3434',
    birth: '1995',
    gender: '여',
    region: '서울',
    jobTypes: ['직장인'],
    insurance4: '가입',
    maritalStatus: '미혼',
    childrenCount: 0,
    incomeDetails: { salary: 200 },
    incomeNet: 200,
    loanMonthlyPay: 10,
    housingType: '자가',
    housingDetail: '아파트',
    ownHousePrice: 50000,
    ownHouseLoan: 0,
    ownHouseOwner: '본인',
    deposit: 0, rent: 0,
    assets: [],
    creditLoan: [],
    historyType: '없음',
    specialMemo: [{ id: 'm-1008', createdAt: subDays(new Date(), 10).toISOString(), content: '자산 과다로 진행 불가 안내함' }],
    depositHistory: [],
    reminders: [],
    recordings: []
  },
  {
    caseId: '1009',
    partnerId: 'P003',
    createdAt: subDays(new Date(), 4).toISOString(),
    updatedAt: subDays(new Date(), 4).toISOString(),
    status: '사무장 접수',
    statusUpdatedAt: subDays(new Date(), 4).toISOString(),
    managerName: 'Mark',
    caseType: '개인회생',
    inboundPath: '구글 검색',
    customerName: '현빈',
    phone: '010-5656-7878',
    birth: '1982',
    gender: '남',
    region: '대전',
    jobTypes: ['개인사업자'],
    insurance4: '미가입',
    maritalStatus: '기혼',
    childrenCount: 2,
    incomeDetails: { business: 600 },
    incomeNet: 600,
    loanMonthlyPay: 250,
    housingType: '전세',
    housingDetail: '아파트',
    deposit: 30000,
    rent: 0,
    rentContractor: '본인',
    depositLoanAmount: 20000,
    assets: [{ id: '3', owner: '배우자', type: '자동차', amount: 4000, loanAmount: 1000, desc: '카니발' }],
    creditLoan: [{ id: 'cl-7', amount: 15000, desc: '사업자 신용' }],
    historyType: '없음',
    specialMemo: [],
    depositHistory: [],
    reminders: [{ id: 'rm-1009', datetime: format(addDays(new Date(), 3), 'yyyy-MM-dd 11:00'), type: '통화' }],
    recordings: []
  },
  {
    caseId: '1010',
    partnerId: 'P001',
    createdAt: subDays(new Date(), 12).toISOString(),
    updatedAt: subDays(new Date(), 2).toISOString(),
    status: '2차 입금완료',
    statusUpdatedAt: subDays(new Date(), 2).toISOString(),
    managerName: 'Mark',
    caseType: '개인회생',
    inboundPath: '메타 광고',
    customerName: '김태희',
    phone: '010-0909-8787',
    birth: '1988',
    gender: '여',
    region: '서울',
    jobTypes: ['직장인'],
    insurance4: '가입',
    maritalStatus: '기혼',
    childrenCount: 1,
    incomeDetails: { salary: 280 },
    incomeNet: 280,
    loanMonthlyPay: 100,
    housingType: '월세',
    housingDetail: '빌라',
    deposit: 3000,
    rent: 80,
    rentContractor: '본인',
    assets: [],
    creditLoan: [{ id: 'cl-8', amount: 4500, desc: '카드론 및 현금서비스' }],
    historyType: '없음',
    contractAt: format(subDays(new Date(), 10), 'yyyy-MM-dd'),
    contractFee: 220,
    deposit1Amount: 110,
    deposit1Date: format(subDays(new Date(), 9), 'yyyy-MM-dd'),
    deposit2Amount: 110,
    deposit2Date: format(subDays(new Date(), 2), 'yyyy-MM-dd'),
    specialMemo: [],
    depositHistory: [],
    reminders: [],
    recordings: []
  },
  {
    caseId: '1011',
    partnerId: 'P002',
    createdAt: subDays(new Date(), 20).toISOString(),
    updatedAt: subDays(new Date(), 5).toISOString(),
    status: '장기관리중',
    statusUpdatedAt: subDays(new Date(), 5).toISOString(),
    managerName: 'Mark',
    caseType: '개인회생',
    inboundPath: '블로그',
    customerName: '전지현',
    phone: '010-1357-2468',
    birth: '1981',
    gender: '여',
    region: '강원',
    jobTypes: ['프리랜서'],
    insurance4: '미가입',
    maritalStatus: '미혼',
    childrenCount: 0,
    incomeDetails: { freelance: 200 },
    incomeNet: 200,
    loanMonthlyPay: 60,
    housingType: '자가',
    housingDetail: '기타',
    ownHousePrice: 15000,
    ownHouseLoan: 12000,
    ownHouseOwner: '본인',
    deposit: 0, rent: 0,
    assets: [],
    creditLoan: [{ id: 'cl-9', amount: 3000, desc: '캐피탈' }],
    historyType: '개인회생',
    historyMemo: '5년 전 폐지됨',
    specialMemo: [{ id: 'm-1011', createdAt: subDays(new Date(), 20).toISOString(), content: '재신청 문의. 비용 마련 후 진행하기로 함' }],
    depositHistory: [],
    reminders: [{ id: 'rm-1011', datetime: format(addDays(new Date(), 15), 'yyyy-MM-dd 10:00'), type: '통화' }],
    recordings: []
  },
  {
    caseId: '1012',
    partnerId: 'P001',
    createdAt: subDays(new Date(), 1).toISOString(),
    updatedAt: subDays(new Date(), 1).toISOString(),
    status: '신규접수',
    statusUpdatedAt: subDays(new Date(), 1).toISOString(),
    managerName: 'Mark',
    caseType: '개인회생',
    inboundPath: '유튜브',
    customerName: '공유',
    phone: '010-2468-1357',
    birth: '1979',
    gender: '남',
    region: '부산',
    jobTypes: ['직장인'],
    insurance4: '가입',
    maritalStatus: '미혼',
    childrenCount: 0,
    incomeDetails: { salary: 350 },
    incomeNet: 350,
    loanMonthlyPay: 180,
    housingType: '전세',
    housingDetail: '오피스텔',
    deposit: 12000,
    rent: 0,
    rentContractor: '본인',
    assets: [{ id: '4', owner: '본인', type: '주식/가상화폐', amount: 500, loanAmount: 0, desc: '코인 손실' }],
    creditLoan: [{ id: 'cl-10', amount: 6000, desc: '은행 및 저축은행' }],
    historyType: '없음',
    specialMemo: [],
    depositHistory: [],
    reminders: [],
    recordings: []
  },
  {
    caseId: '1013',
    partnerId: 'P003',
    createdAt: subDays(new Date(), 0).toISOString(),
    updatedAt: subDays(new Date(), 0).toISOString(),
    status: '신규접수',
    statusUpdatedAt: subDays(new Date(), 0).toISOString(),
    managerName: 'Mark',
    caseType: '개인회생',
    inboundPath: '틱톡 광고',
    customerName: '송혜교',
    phone: '010-9876-1234',
    birth: '1981',
    gender: '여',
    region: '서울',
    jobTypes: ['무직'],
    insurance4: '미가입',
    maritalStatus: '이혼',
    childrenCount: 1,
    incomeDetails: {},
    incomeNet: 0,
    loanMonthlyPay: 0,
    housingType: '무상거주',
    housingDetail: '아파트',
    freeHousingOwner: '지인',
    deposit: 0, rent: 0,
    assets: [],
    creditLoan: [{ id: 'cl-11', amount: 2500, desc: '생활비 대출' }],
    historyType: '없음',
    specialMemo: [{ id: 'm-1013', createdAt: new Date().toISOString(), content: '취업 예정이라고 함' }],
    depositHistory: [],
    reminders: [],
    recordings: []
  },
  {
    caseId: '1014',
    partnerId: 'P002',
    createdAt: subDays(new Date(), 2).toISOString(),
    updatedAt: subDays(new Date(), 1).toISOString(),
    status: '재통화 예정',
    statusUpdatedAt: subDays(new Date(), 1).toISOString(),
    managerName: 'Mark',
    caseType: '신용회복',
    inboundPath: '지인 소개',
    customerName: '이정재',
    phone: '010-1122-3344',
    birth: '1972',
    gender: '남',
    region: '서울',
    jobTypes: ['법인사업자'],
    insurance4: '가입',
    maritalStatus: '미혼',
    childrenCount: 0,
    incomeDetails: { business: 800 },
    incomeNet: 800,
    loanMonthlyPay: 400,
    housingType: '자가',
    housingDetail: '아파트',
    ownHousePrice: 120000,
    ownHouseLoan: 80000,
    ownHouseOwner: '본인',
    deposit: 0, rent: 0,
    assets: [{ id: '5', owner: '본인', type: '자동차', amount: 8000, loanAmount: 0, desc: '벤츠' }],
    creditLoan: [{ id: 'cl-12', amount: 20000, desc: '법인 연대보증' }],
    historyType: '없음',
    specialMemo: [],
    depositHistory: [],
    reminders: [{ id: 'rm-1014', datetime: format(addDays(new Date(), 0), 'yyyy-MM-dd 16:00'), type: '통화' }],
    recordings: []
  },
  {
    caseId: '1015',
    partnerId: 'P001',
    createdAt: subDays(new Date(), 3).toISOString(),
    updatedAt: subDays(new Date(), 3).toISOString(),
    status: '부재',
    statusUpdatedAt: subDays(new Date(), 3).toISOString(),
    managerName: 'Mark',
    caseType: '개인회생',
    inboundPath: '메타 광고',
    customerName: '한효주',
    phone: '010-5544-3322',
    birth: '1987',
    gender: '여',
    region: '경기',
    jobTypes: ['직장인'],
    insurance4: '가입',
    maritalStatus: '미혼',
    childrenCount: 0,
    incomeDetails: { salary: 230 },
    incomeNet: 230,
    loanMonthlyPay: 70,
    housingType: '월세',
    housingDetail: '오피스텔',
    deposit: 1000,
    rent: 55,
    rentContractor: '본인',
    assets: [],
    creditLoan: [{ id: 'cl-13', amount: 3500, desc: '학자금 및 생활비' }],
    historyType: '없음',
    specialMemo: [],
    depositHistory: [],
    reminders: [{ id: 'rm-1015', datetime: format(addDays(new Date(), 1), 'yyyy-MM-dd 09:30'), type: '통화' }],
    recordings: []
  },
  {
    caseId: '1016',
    partnerId: 'P002',
    createdAt: subDays(new Date(), 6).toISOString(),
    updatedAt: subDays(new Date(), 6).toISOString(),
    status: '고객취소',
    statusUpdatedAt: subDays(new Date(), 6).toISOString(),
    managerName: 'Mark',
    caseType: '개인회생',
    inboundPath: '유튜브',
    customerName: '박서준',
    phone: '010-6677-8899',
    birth: '1988',
    gender: '남',
    region: '서울',
    jobTypes: ['직장인'],
    insurance4: '가입',
    maritalStatus: '미혼',
    childrenCount: 0,
    incomeDetails: { salary: 290 },
    incomeNet: 290,
    loanMonthlyPay: 90,
    housingType: '전세',
    housingDetail: '빌라',
    deposit: 18000,
    rent: 0,
    rentContractor: '본인',
    assets: [],
    creditLoan: [{ id: 'cl-14', amount: 5000, desc: '은행' }],
    historyType: '없음',
    specialMemo: [{ id: 'm-1016', createdAt: subDays(new Date(), 6).toISOString(), content: '가족 도움으로 해결한다고 함' }],
    depositHistory: [],
    reminders: [],
    recordings: []
  },
  {
    caseId: '1017',
    partnerId: 'P003',
    createdAt: subDays(new Date(), 8).toISOString(),
    updatedAt: subDays(new Date(), 1).toISOString(),
    status: '계약 완료',
    statusUpdatedAt: subDays(new Date(), 1).toISOString(),
    managerName: 'Mark',
    caseType: '개인회생',
    inboundPath: '구글 검색',
    customerName: '아이유',
    phone: '010-9988-7766',
    birth: '1993',
    gender: '여',
    region: '서울',
    jobTypes: ['프리랜서'],
    insurance4: '미가입',
    maritalStatus: '미혼',
    childrenCount: 0,
    incomeDetails: { freelance: 500 },
    incomeNet: 500,
    loanMonthlyPay: 100,
    housingType: '자가',
    housingDetail: '아파트',
    ownHousePrice: 80000,
    ownHouseLoan: 40000,
    ownHouseOwner: '본인',
    deposit: 0, rent: 0,
    assets: [],
    creditLoan: [{ id: 'cl-15', amount: 6000, desc: '2금융권' }],
    historyType: '없음',
    contractAt: format(subDays(new Date(), 1), 'yyyy-MM-dd'),
    contractFee: 250,
    specialMemo: [],
    depositHistory: [],
    reminders: [],
    recordings: []
  }
];

export const MOCK_LOGS: CaseStatusLog[] = [];
